permissions:
  id-token: write # Требуется для запроса JWT-токена

on:
  workflow_dispatch:

jobs:
  ansible:
    runs-on: ubuntu-latest
    steps:
      - name: Get Yandex Cloud IAM token
        id: get-iam-token
        uses: docker://ghcr.io/yc-actions/yc-iam-token-fed:1.0.0
        with:
          yc-sa-id: ajeoorepccueu6hhe4vn

      - name: GetLockboxPayload
        run: |
          SECRET_ID="e6q0t0b0r7550ctrpia3"
          SECRET_DATA=$(curl -sH "Authorization: Bearer ${{steps.get-iam-token.outputs.token}}" https://payload.lockbox.api.cloud.yandex.net/lockbox/v1/secrets/$SECRET_ID/payload)
          {
            echo "SECRET_DATA<<EOF"
            echo "$SECRET_DATA"
            echo "EOF"
          } >> "$GITHUB_OUTPUT"

        id: getlockboxpayload
